/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects, newest first, with item and listing counts */
        get: operations["listProjects"];
        put?: never;
        /** Create a project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** Get a project */
        get: operations["getProject"];
        /** Replace a project's name and description */
        put: operations["updateProject"];
        post?: never;
        /** Delete a project with all its items, listings and offers */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** Status counts, per-currency totals and gaps of a project */
        get: operations["getProjectSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** List the items of a project in the order they were added */
        get: operations["listProjectItems"];
        put?: never;
        /** Add an item to a project */
        post: operations["createItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        /** Get an item */
        get: operations["getItem"];
        /** Replace an item's name, quantity and notes */
        put: operations["updateItem"];
        post?: never;
        /** Delete an item and its offers */
        delete: operations["deleteItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/items/{itemId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set an item's sourcing status (any transition) */
        patch: operations["setItemStatus"];
        trace?: never;
    };
    "/api/items/{itemId}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        /** List the offers of an item in the order they were created */
        get: operations["listItemOffers"];
        put?: never;
        /** Link the item to a listing of the same project */
        post: operations["createOffer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{projectId}/listings": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        /** List the listings of a project in the order they were added */
        get: operations["listProjectListings"];
        put?: never;
        /** Add a listing to a project */
        post: operations["createListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        /** Get a listing */
        get: operations["getListing"];
        /** Replace a listing's fields other than the status */
        put: operations["updateListing"];
        post?: never;
        /** Delete a listing and its offers; the linked items stay */
        delete: operations["deleteListing"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/listings/{listingId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set a listing's negotiation status (any transition) */
        patch: operations["setListingStatus"];
        trace?: never;
    };
    "/api/listings/{listingId}/offers": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        /** List the offers of a listing (across items) in the order they were created */
        get: operations["listListingOffers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace the asking and agreed unit prices (null clears a price) */
        put: operations["updateOffer"];
        post?: never;
        /** Delete an offer */
        delete: operations["deleteOffer"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/offers/{offerId}/fit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set whether the offered part fits */
        patch: operations["setOfferFit"];
        trace?: never;
    };
    "/api/offers/{offerId}/choice": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Choose (auto-switching the item's previous choice) or un-choose an offer */
        patch: operations["setOfferChoice"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ItemStatus: "Needed" | "Sourcing" | "Ordered" | "Received";
        /** @enum {string} */
        ListingStatus: "Found" | "Contacted" | "Negotiating" | "Agreed" | "Purchased" | "Received" | "NotResponding" | "Declined" | "Scam";
        /** @enum {string} */
        OfferFit: "Unverified" | "Fits" | "NotQuiteRight" | "WrongItem";
        /** @description An amount in one currency. Never converted between currencies. */
        Money: {
            amount: number;
            /** @description An active ISO 4217 code, e.g. UAH, EUR, USD, PLN. Unknown codes (e.g. ZZZ) and special non-currency codes (e.g. XXX, XAU, XDR) are rejected with 400. */
            currency: string;
        };
        /** @description An aggregated amount in one currency (Σ unit price × quantity). It has no upper bound, because a total may exceed the single-price limit. */
        MoneyTotal: {
            amount: number;
            currency: string;
        };
        ProjectInput: {
            name: string;
            description?: string | null;
        };
        Project: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ProjectListEntry: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: int32 */
            itemCount: number;
            /** Format: int32 */
            listingCount: number;
        };
        /** @description Item count per ItemStatus value (camelCase keys); every status is present, 0 when empty */
        ItemCountsByStatus: {
            /** Format: int32 */
            needed: number;
            /** Format: int32 */
            sourcing: number;
            /** Format: int32 */
            ordered: number;
            /** Format: int32 */
            received: number;
        };
        ItemRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        OfferRef: {
            /** Format: uuid */
            offerId: string;
            /** Format: uuid */
            itemId: string;
            itemName: string;
            /** Format: uuid */
            listingId: string;
            listingTitle: string;
        };
        ProjectSummary: {
            /** Format: uuid */
            projectId: string;
            itemCountsByStatus: components["schemas"]["ItemCountsByStatus"];
            /** @description One entry per currency, ordered by currency code; Σ (agreed ?? asking) × quantity over chosen offers */
            totals: components["schemas"]["MoneyTotal"][];
            itemsWithoutChosenOffer: components["schemas"]["ItemRef"][];
            chosenOffersWithoutPrice: components["schemas"]["OfferRef"][];
        };
        ItemInput: {
            name: string;
            /** Format: int32 */
            quantity: number;
            notes?: string | null;
        };
        ItemStatusUpdate: {
            status: components["schemas"]["ItemStatus"];
        };
        ChosenOfferSummary: {
            /** Format: uuid */
            offerId: string;
            /** Format: uuid */
            listingId: string;
            listingTitle: string;
            /** @description Agreed price if set, otherwise asking price; null when neither is set */
            unitPrice: components["schemas"]["Money"] | null;
        };
        Item: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            name: string;
            /** Format: int32 */
            quantity: number;
            notes: string | null;
            status: components["schemas"]["ItemStatus"];
            chosenOffer: components["schemas"]["ChosenOfferSummary"] | null;
        };
        ListingInput: {
            title: string;
            /**
             * Format: uri
             * @description Absolute http or https URL
             */
            url: string;
            /** @description Free text; the UI suggests OLX, eBay, Allegro, Amazon, Rozetka, Prom */
            platform: string;
            sellerName?: string | null;
            sellerContact?: string | null;
            notes?: string | null;
            agreedTotal?: components["schemas"]["Money"] | null;
        };
        ListingStatusUpdate: {
            status: components["schemas"]["ListingStatus"];
        };
        Listing: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            projectId: string;
            title: string;
            /** Format: uri */
            url: string;
            platform: string;
            sellerName: string | null;
            sellerContact: string | null;
            notes: string | null;
            agreedTotal: components["schemas"]["Money"] | null;
            status: components["schemas"]["ListingStatus"];
            /** Format: date-time */
            statusChangedAt: string;
        };
        OfferCreate: {
            /** Format: uuid */
            listingId: string;
            /** @description Unit price asked by the seller */
            askingPrice?: components["schemas"]["Money"] | null;
            /** @description Unit price agreed with the seller */
            agreedPrice?: components["schemas"]["Money"] | null;
        };
        OfferUpdate: {
            askingPrice: components["schemas"]["Money"] | null;
            agreedPrice: components["schemas"]["Money"] | null;
        };
        OfferFitUpdate: {
            fit: components["schemas"]["OfferFit"];
        };
        OfferChoiceUpdate: {
            isChosen: boolean;
        };
        Offer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            itemId: string;
            itemName: string;
            /** Format: uuid */
            listingId: string;
            listingTitle: string;
            listingPlatform: string;
            listingStatus: components["schemas"]["ListingStatus"];
            askingPrice: components["schemas"]["Money"] | null;
            agreedPrice: components["schemas"]["Money"] | null;
            fit: components["schemas"]["OfferFit"];
            isChosen: boolean;
        };
        /** @description RFC 9457 problem details */
        ProblemDetails: {
            type?: string | null;
            title?: string | null;
            /** Format: int32 */
            status?: number | null;
            detail?: string | null;
            instance?: string | null;
        };
        /** @description RFC 9457 problem details for a violated business rule; `type` names the rule */
        RuleViolationProblemDetails: {
            /** @description /problems/duplicate-offer or /problems/listing-in-other-project */
            type: string;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string | null;
            instance?: string | null;
        };
        /** @description RFC 9457 problem details with field errors keyed by JSON property path (e.g. "askingPrice.amount") */
        ValidationProblemDetails: {
            type?: string | null;
            title: string;
            /** Format: int32 */
            status: number;
            detail?: string | null;
            instance?: string | null;
            errors: {
                [key: string]: string[];
            };
        };
    };
    responses: {
        /** @description Invalid input */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblemDetails"];
            };
        };
        /** @description Unknown id */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description Business rule violated (type /problems/duplicate-offer or /problems/listing-in-other-project) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["RuleViolationProblemDetails"];
            };
        };
    };
    parameters: {
        projectId: string;
        itemId: string;
        listingId: string;
        offerId: string;
    };
    requestBodies: never;
    headers: {
        /** @description URL of the created resource */
        Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListEntry"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectInput"];
            };
        };
        responses: {
            /** @description The updated project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getProjectSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status counts, per-currency totals and gaps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listProjectItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemInput"];
            };
        };
        responses: {
            /** @description Created (status Needed) */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemInput"];
            };
        };
        responses: {
            /** @description The updated item (status unchanged) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    setItemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ItemStatusUpdate"];
            };
        };
        responses: {
            /** @description The item with the new status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listItemOffers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: components["parameters"]["itemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferCreate"];
            };
        };
        responses: {
            /** @description Created (fit Unverified, not chosen) */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listProjectListings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    createListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projectId: components["parameters"]["projectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingInput"];
            };
        };
        responses: {
            /** @description Created (status Found) */
            201: {
                headers: {
                    Location: components["headers"]["Location"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    getListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingInput"];
            };
        };
        responses: {
            /** @description The updated listing (status and statusChangedAt unchanged) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteListing: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    setListingStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ListingStatusUpdate"];
            };
        };
        responses: {
            /** @description The listing with the new status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Listing"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listListingOffers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: components["parameters"]["listingId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferUpdate"];
            };
        };
        responses: {
            /** @description The updated offer (fit and choice unchanged) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteOffer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    setOfferFit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferFitUpdate"];
            };
        };
        responses: {
            /** @description The offer with the new fit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    setOfferChoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                offerId: components["parameters"]["offerId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferChoiceUpdate"];
            };
        };
        responses: {
            /** @description The offer with the new choice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Offer"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
}
